// <auto-generated />
using System;
using System.Collections.Generic;
using IIM.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IIM.Infrastructure.Migrations.GovernanceDb
{
    [DbContext(typeof(GovernanceDbContext))]
    [Migration("20251206215003_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassificationTagStoredFile", b =>
                {
                    b.Property<Guid>("ClassificationTagsId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoredFilesHash")
                        .HasColumnType("text");

                    b.HasKey("ClassificationTagsId", "StoredFilesHash");

                    b.HasIndex("StoredFilesHash");

                    b.ToTable("StoredFileClassificationTags", (string)null);
                });

            modelBuilder.Entity("IIM.Shared.Models.ChainOfCustodyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VirtualFileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VirtualFileId");

                    b.ToTable("ChainOfCustodyEntry");
                });

            modelBuilder.Entity("IIM.Shared.Models.Core.AccessControlRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccessRoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassificationTagId")
                        .HasColumnType("uuid");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccessRoleId");

                    b.HasIndex("ClassificationTagId");

                    b.ToTable("AccessControlRules");
                });

            modelBuilder.Entity("IIM.Shared.Models.Core.AccessRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AccessRoles");
                });

            modelBuilder.Entity("IIM.Shared.Models.Core.ClassificationTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ClassificationTags");
                });

            modelBuilder.Entity("IIM.Shared.Models.Core.StorageTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EncryptionRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("Location")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RetentionPeriodDays")
                        .HasColumnType("integer");

                    b.Property<string>("SeaweedFSCollection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StorageTiers");
                });

            modelBuilder.Entity("IIM.Shared.Models.Core.StoredFile", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentSummary")
                        .HasColumnType("text");

                    b.Property<string>("DetectedEntitiesJson")
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstSeenBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FirstWorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsQuarantined")
                        .HasColumnType("boolean");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PerceptualHash")
                        .HasColumnType("text");

                    b.Property<double?>("PerceptualQuality")
                        .HasColumnType("double precision");

                    b.Property<string>("QuarantineReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("QuarantinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Hash");

                    b.ToTable("StoredFile");
                });

            modelBuilder.Entity("IIM.Shared.Models.ProcessedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OriginalVirtualFileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoredFileHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("VirtualFileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VirtualFileId");

                    b.ToTable("ProcessedFile");
                });

            modelBuilder.Entity("IIM.Shared.Models.VirtualFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CollectedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CollectedLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CollectionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomMetadataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DataSensitivity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProposedSensitiviyLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SensitivityLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StoredFileHash")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StoredFileHash");

                    b.ToTable("VirtualFile");
                });

            modelBuilder.Entity("ClassificationTagStoredFile", b =>
                {
                    b.HasOne("IIM.Shared.Models.Core.ClassificationTag", null)
                        .WithMany()
                        .HasForeignKey("ClassificationTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIM.Shared.Models.Core.StoredFile", null)
                        .WithMany()
                        .HasForeignKey("StoredFilesHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IIM.Shared.Models.ChainOfCustodyEntry", b =>
                {
                    b.HasOne("IIM.Shared.Models.VirtualFile", null)
                        .WithMany("ChainOfCustody")
                        .HasForeignKey("VirtualFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IIM.Shared.Models.Core.AccessControlRule", b =>
                {
                    b.HasOne("IIM.Shared.Models.Core.AccessRole", "AccessRole")
                        .WithMany()
                        .HasForeignKey("AccessRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIM.Shared.Models.Core.ClassificationTag", "ClassificationTag")
                        .WithMany()
                        .HasForeignKey("ClassificationTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessRole");

                    b.Navigation("ClassificationTag");
                });

            modelBuilder.Entity("IIM.Shared.Models.ProcessedFile", b =>
                {
                    b.HasOne("IIM.Shared.Models.VirtualFile", null)
                        .WithMany("ProcessedVersions")
                        .HasForeignKey("VirtualFileId");
                });

            modelBuilder.Entity("IIM.Shared.Models.VirtualFile", b =>
                {
                    b.HasOne("IIM.Shared.Models.Core.StoredFile", null)
                        .WithMany("VirtualFiles")
                        .HasForeignKey("StoredFileHash");
                });

            modelBuilder.Entity("IIM.Shared.Models.Core.StoredFile", b =>
                {
                    b.Navigation("VirtualFiles");
                });

            modelBuilder.Entity("IIM.Shared.Models.VirtualFile", b =>
                {
                    b.Navigation("ChainOfCustody");

                    b.Navigation("ProcessedVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
