// <auto-generated />
using System;
using System.Collections.Generic;
using IIM.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IIM.Infrastructure.Migrations.GovernanceDb
{
    [DbContext(typeof(GovernanceDbContext))]
    [Migration("20260102233923_UpdateGovernace060102")]
    partial class UpdateGovernace060102
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassificationTagStoredFile", b =>
                {
                    b.Property<Guid>("ClassificationTagsId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoredFilesBlake3Hash")
                        .HasColumnType("character varying(64)");

                    b.HasKey("ClassificationTagsId", "StoredFilesBlake3Hash");

                    b.HasIndex("StoredFilesBlake3Hash");

                    b.ToTable("StoredFileClassificationTags", (string)null);
                });

            modelBuilder.Entity("IIM.Shared.Models.ChainOfCustodyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VirtualFileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VirtualFileId");

                    b.ToTable("ChainOfCustodyEntry");
                });

            modelBuilder.Entity("IIM.Shared.Models.Core.AccessControlRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccessRoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassificationTagId")
                        .HasColumnType("uuid");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccessRoleId");

                    b.HasIndex("ClassificationTagId");

                    b.ToTable("AccessControlRules");
                });

            modelBuilder.Entity("IIM.Shared.Models.Core.AccessRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AccessRoles");
                });

            modelBuilder.Entity("IIM.Shared.Models.Core.ClassificationTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ClassificationTags");
                });

            modelBuilder.Entity("IIM.Shared.Models.Core.StorageTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EncryptionRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("Location")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RetentionPeriodDays")
                        .HasColumnType("integer");

                    b.Property<string>("SeaweedFSCollection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StorageTiers");
                });

            modelBuilder.Entity("IIM.Shared.Models.ProcessedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DerivedHash")
                        .HasColumnType("text");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParametersHash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessorKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessorVersion")
                        .HasColumnType("text");

                    b.Property<string>("StoredFileBlake3Hash")
                        .HasColumnType("character varying(64)");

                    b.Property<string>("StoredFileHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StoredFileBlake3Hash");

                    b.ToTable("ProcessedFile");
                });

            modelBuilder.Entity("IIM.Shared.Models.StoredFile", b =>
                {
                    b.Property<string>("Blake3Hash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("integer");

                    b.Property<string>("ContentSummary")
                        .HasColumnType("text");

                    b.Property<string>("DetectedEntitiesJson")
                        .HasColumnType("text");

                    b.Property<int>("EntityCount")
                        .HasColumnType("integer");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstSeenBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FirstWorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("GraphRagMetadataJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("IndexedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsIndexed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsQuarantined")
                        .HasColumnType("boolean");

                    b.Property<string>("Md5Hash")
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PerceptualHash")
                        .HasColumnType("text");

                    b.Property<double?>("PerceptualQuality")
                        .HasColumnType("double precision");

                    b.Property<string>("QuarantineReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("QuarantinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sha256Hash")
                        .HasColumnType("text");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Blake3Hash");

                    b.ToTable("StoredFile");
                });

            modelBuilder.Entity("VirtualFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, string>>("CustomMetadata")
                        .IsRequired()
                        .HasColumnType("hstore");

                    b.Property<string>("CustomMetadataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Dictionary<string, string>>("EnrichmentMetadata")
                        .IsRequired()
                        .HasColumnType("hstore");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProposedLabel")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StoredFileBlake3Hash")
                        .HasColumnType("character varying(64)");

                    b.Property<string>("StoredFileHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StoredFileBlake3Hash");

                    b.ToTable("VirtualFile");
                });

            modelBuilder.Entity("ClassificationTagStoredFile", b =>
                {
                    b.HasOne("IIM.Shared.Models.Core.ClassificationTag", null)
                        .WithMany()
                        .HasForeignKey("ClassificationTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIM.Shared.Models.StoredFile", null)
                        .WithMany()
                        .HasForeignKey("StoredFilesBlake3Hash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IIM.Shared.Models.ChainOfCustodyEntry", b =>
                {
                    b.HasOne("VirtualFile", null)
                        .WithMany("ChainOfCustody")
                        .HasForeignKey("VirtualFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IIM.Shared.Models.Core.AccessControlRule", b =>
                {
                    b.HasOne("IIM.Shared.Models.Core.AccessRole", "AccessRole")
                        .WithMany()
                        .HasForeignKey("AccessRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIM.Shared.Models.Core.ClassificationTag", "ClassificationTag")
                        .WithMany()
                        .HasForeignKey("ClassificationTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessRole");

                    b.Navigation("ClassificationTag");
                });

            modelBuilder.Entity("IIM.Shared.Models.ProcessedFile", b =>
                {
                    b.HasOne("IIM.Shared.Models.StoredFile", "StoredFile")
                        .WithMany("ProcessedVersions")
                        .HasForeignKey("StoredFileBlake3Hash");

                    b.Navigation("StoredFile");
                });

            modelBuilder.Entity("VirtualFile", b =>
                {
                    b.HasOne("IIM.Shared.Models.StoredFile", "StoredFile")
                        .WithMany("VirtualFiles")
                        .HasForeignKey("StoredFileBlake3Hash");

                    b.Navigation("StoredFile");
                });

            modelBuilder.Entity("IIM.Shared.Models.StoredFile", b =>
                {
                    b.Navigation("ProcessedVersions");

                    b.Navigation("VirtualFiles");
                });

            modelBuilder.Entity("VirtualFile", b =>
                {
                    b.Navigation("ChainOfCustody");
                });
#pragma warning restore 612, 618
        }
    }
}
