<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Models\Analysis\" />
    <Folder Include="Models\Audit\" />
    <Folder Include="Models\Configuration\" />
    <Folder Include="Models\Investigation\" />
    <Folder Include="Models\Reporting\" />
    <Folder Include="Models\Storage\" />
    <Folder Include="Models\Supporting\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.22.1" />
  </ItemGroup>
</Project>

