// <auto-generated />
using System;
using System.Collections.Generic;
using IIM.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IIM.Infrastructure.Migrations.WorkspaceDb
{
    [DbContext(typeof(WorkspaceDbContext))]
    [Migration("20251216050148_RemoveUserForeignKey")]
    partial class RemoveUserForeignKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassificationTagStoredFile", b =>
                {
                    b.Property<Guid>("ClassificationTagsId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoredFilesBlake3Hash")
                        .HasColumnType("character varying(64)");

                    b.HasKey("ClassificationTagsId", "StoredFilesBlake3Hash");

                    b.HasIndex("StoredFilesBlake3Hash");

                    b.ToTable("ClassificationTagStoredFile");
                });

            modelBuilder.Entity("IIM.Shared.Models.ChainOfCustodyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VirtualFileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VirtualFileId");

                    b.ToTable("ChainOfCustodyEntry");
                });

            modelBuilder.Entity("IIM.Shared.Models.Core.ClassificationTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ClassificationTags");
                });

            modelBuilder.Entity("IIM.Shared.Models.Core.ProcessedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Dictionary<string, string>>("Metadata")
                        .IsRequired()
                        .HasColumnType("hstore");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoredFileHash")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("VirtualFileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StoredFileHash");

                    b.HasIndex("VirtualFileId");

                    b.ToTable("ProcessedFiles");
                });

            modelBuilder.Entity("IIM.Shared.Models.Core.StoredFile", b =>
                {
                    b.Property<string>("Blake3Hash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("integer");

                    b.Property<string>("ContentSummary")
                        .HasColumnType("text");

                    b.Property<string>("DetectedEntitiesJson")
                        .HasColumnType("text");

                    b.Property<int>("EntityCount")
                        .HasColumnType("integer");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstSeenBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FirstWorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("GraphRagMetadataJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("IndexedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsIndexed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsQuarantined")
                        .HasColumnType("boolean");

                    b.Property<string>("Md5Hash")
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PerceptualHash")
                        .HasColumnType("text");

                    b.Property<double?>("PerceptualQuality")
                        .HasColumnType("double precision");

                    b.Property<string>("QuarantineReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("QuarantinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sha256Hash")
                        .HasColumnType("text");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Blake3Hash");

                    b.ToTable("StoredFiles");
                });

            modelBuilder.Entity("IIM.Shared.Models.TimelineEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssociatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssociatedEntityType")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("TimelineEvents");
                });

            modelBuilder.Entity("IIM.Shared.Models.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("IIM.Shared.Models.WorkspaceArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("WorkspaceArtifacts");
                });

            modelBuilder.Entity("IIM.Shared.Models.WorkspaceFile", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VirtualFileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WorkspaceId", "VirtualFileId");

                    b.HasIndex("VirtualFileId");

                    b.ToTable("WorkspaceFiles");
                });

            modelBuilder.Entity("IIM.Shared.Models.WorkspaceSession", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WorkspaceId", "SessionId");

                    b.ToTable("WorkspaceSessions");
                });

            modelBuilder.Entity("IIM.Shared.Models.WorkspaceUser", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("WorkspaceId", "UserId");

                    b.ToTable("WorkspaceUsers");
                });

            modelBuilder.Entity("VirtualFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, string>>("CustomMetadata")
                        .IsRequired()
                        .HasColumnType("hstore");

                    b.Property<string>("CustomMetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, string>>("EnrichmentMetadata")
                        .IsRequired()
                        .HasColumnType("hstore");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProposedLabel")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StoredFileHash")
                        .HasColumnType("character varying(64)");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StoredFileHash");

                    b.ToTable("VirtualFiles");
                });

            modelBuilder.Entity("ClassificationTagStoredFile", b =>
                {
                    b.HasOne("IIM.Shared.Models.Core.ClassificationTag", null)
                        .WithMany()
                        .HasForeignKey("ClassificationTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIM.Shared.Models.Core.StoredFile", null)
                        .WithMany()
                        .HasForeignKey("StoredFilesBlake3Hash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IIM.Shared.Models.ChainOfCustodyEntry", b =>
                {
                    b.HasOne("VirtualFile", null)
                        .WithMany("ChainOfCustody")
                        .HasForeignKey("VirtualFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IIM.Shared.Models.Core.ProcessedFile", b =>
                {
                    b.HasOne("IIM.Shared.Models.Core.StoredFile", "StoredFile")
                        .WithMany("ProcessedVersions")
                        .HasForeignKey("StoredFileHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VirtualFile", "VirtualFile")
                        .WithMany()
                        .HasForeignKey("VirtualFileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("StoredFile");

                    b.Navigation("VirtualFile");
                });

            modelBuilder.Entity("IIM.Shared.Models.TimelineEvent", b =>
                {
                    b.HasOne("IIM.Shared.Models.Workspace", null)
                        .WithMany("TimelineEvents")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IIM.Shared.Models.WorkspaceFile", b =>
                {
                    b.HasOne("VirtualFile", "VirtualFile")
                        .WithMany()
                        .HasForeignKey("VirtualFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIM.Shared.Models.Workspace", "Workspace")
                        .WithMany("Files")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VirtualFile");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("IIM.Shared.Models.WorkspaceSession", b =>
                {
                    b.HasOne("IIM.Shared.Models.Workspace", "Workspace")
                        .WithMany("Sessions")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("IIM.Shared.Models.WorkspaceUser", b =>
                {
                    b.HasOne("IIM.Shared.Models.Workspace", null)
                        .WithMany("Users")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VirtualFile", b =>
                {
                    b.HasOne("IIM.Shared.Models.Core.StoredFile", "StoredFile")
                        .WithMany("VirtualFiles")
                        .HasForeignKey("StoredFileHash")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("StoredFile");
                });

            modelBuilder.Entity("IIM.Shared.Models.Core.StoredFile", b =>
                {
                    b.Navigation("ProcessedVersions");

                    b.Navigation("VirtualFiles");
                });

            modelBuilder.Entity("IIM.Shared.Models.Workspace", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Sessions");

                    b.Navigation("TimelineEvents");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("VirtualFile", b =>
                {
                    b.Navigation("ChainOfCustody");
                });
#pragma warning restore 612, 618
        }
    }
}
