// <auto-generated />
using System;
using System.Collections.Generic;
using IIM.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IIM.Infrastructure.Migrations.WorkspaceDb
{
    [DbContext(typeof(WorkspaceDbContext))]
    partial class WorkspaceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IIM.Shared.Models.ChainOfCustodyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VirtualFileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VirtualFileId");

                    b.ToTable("ChainOfCustodyEntry");
                });

            modelBuilder.Entity("IIM.Shared.Models.Core.ClassificationTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ClassificationTags");
                });

            modelBuilder.Entity("IIM.Shared.Models.Core.StoredFile", b =>
                {
                    b.Property<string>("Hash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentSummary")
                        .HasColumnType("text");

                    b.Property<string>("DetectedEntitiesJson")
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstSeenBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FirstWorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsQuarantined")
                        .HasColumnType("boolean");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PerceptualHash")
                        .HasColumnType("text");

                    b.Property<double?>("PerceptualQuality")
                        .HasColumnType("double precision");

                    b.Property<string>("QuarantineReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("QuarantinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Hash");

                    b.ToTable("StoredFiles");
                });

            modelBuilder.Entity("IIM.Shared.Models.InvestigationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("InvestigationSession");
                });

            modelBuilder.Entity("IIM.Shared.Models.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HiddenReasoning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("InvestigationSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReasoning")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InvestigationSessionId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("IIM.Shared.Models.MessageAttachment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Data")
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MessageId")
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("MessageAttachment");
                });

            modelBuilder.Entity("IIM.Shared.Models.ProcessedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OriginalVirtualFileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoredFileHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("VirtualFileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VirtualFileId");

                    b.ToTable("ProcessedFile");
                });

            modelBuilder.Entity("IIM.Shared.Models.TimelineEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssociatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssociatedEntityType")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("TimelineEvents");
                });

            modelBuilder.Entity("IIM.Shared.Models.VirtualFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CollectedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CollectedLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CollectionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomMetadataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DataSensitivity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProposedSensitiviyLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SensitivityLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StoredFileHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StoredFileHash");

                    b.ToTable("VirtualFiles");
                });

            modelBuilder.Entity("IIM.Shared.Models.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("IIM.Shared.Models.WorkspaceArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("WorkspaceArtifacts");
                });

            modelBuilder.Entity("IIM.Shared.Models.WorkspaceFile", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VirtualFileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WorkspaceId", "VirtualFileId");

                    b.HasIndex("VirtualFileId");

                    b.ToTable("WorkspaceFiles");
                });

            modelBuilder.Entity("IIM.Shared.Models.WorkspaceSession", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WorkspaceId", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("WorkspaceSessions");
                });

            modelBuilder.Entity("IIM.Shared.Models.WorkspaceUser", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("WorkspaceId", "UserId");

                    b.ToTable("WorkspaceUsers");
                });

            modelBuilder.Entity("StoredFileClassificationTag", b =>
                {
                    b.Property<Guid>("ClassificationTagId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoredFileHash")
                        .HasColumnType("character varying(256)");

                    b.HasKey("ClassificationTagId", "StoredFileHash");

                    b.HasIndex("StoredFileHash");

                    b.ToTable("StoredFileClassificationTag");
                });

            modelBuilder.Entity("IIM.Shared.Models.ChainOfCustodyEntry", b =>
                {
                    b.HasOne("IIM.Shared.Models.VirtualFile", null)
                        .WithMany("ChainOfCustody")
                        .HasForeignKey("VirtualFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IIM.Shared.Models.Message", b =>
                {
                    b.HasOne("IIM.Shared.Models.InvestigationSession", null)
                        .WithMany("Messages")
                        .HasForeignKey("InvestigationSessionId");
                });

            modelBuilder.Entity("IIM.Shared.Models.MessageAttachment", b =>
                {
                    b.HasOne("IIM.Shared.Models.Message", null)
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId");
                });

            modelBuilder.Entity("IIM.Shared.Models.ProcessedFile", b =>
                {
                    b.HasOne("IIM.Shared.Models.VirtualFile", null)
                        .WithMany("ProcessedVersions")
                        .HasForeignKey("VirtualFileId");
                });

            modelBuilder.Entity("IIM.Shared.Models.TimelineEvent", b =>
                {
                    b.HasOne("IIM.Shared.Models.Workspace", null)
                        .WithMany("TimelineEvents")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IIM.Shared.Models.VirtualFile", b =>
                {
                    b.HasOne("IIM.Shared.Models.Core.StoredFile", null)
                        .WithMany("VirtualFiles")
                        .HasForeignKey("StoredFileHash")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("IIM.Shared.Models.WorkspaceFile", b =>
                {
                    b.HasOne("IIM.Shared.Models.VirtualFile", "VirtualFile")
                        .WithMany()
                        .HasForeignKey("VirtualFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIM.Shared.Models.Workspace", "Workspace")
                        .WithMany("Files")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VirtualFile");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("IIM.Shared.Models.WorkspaceSession", b =>
                {
                    b.HasOne("IIM.Shared.Models.InvestigationSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIM.Shared.Models.Workspace", "Workspace")
                        .WithMany("Sessions")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("IIM.Shared.Models.WorkspaceUser", b =>
                {
                    b.HasOne("IIM.Shared.Models.Workspace", null)
                        .WithMany("Users")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StoredFileClassificationTag", b =>
                {
                    b.HasOne("IIM.Shared.Models.Core.ClassificationTag", null)
                        .WithMany()
                        .HasForeignKey("ClassificationTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIM.Shared.Models.Core.StoredFile", null)
                        .WithMany()
                        .HasForeignKey("StoredFileHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IIM.Shared.Models.Core.StoredFile", b =>
                {
                    b.Navigation("VirtualFiles");
                });

            modelBuilder.Entity("IIM.Shared.Models.InvestigationSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("IIM.Shared.Models.Message", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("IIM.Shared.Models.VirtualFile", b =>
                {
                    b.Navigation("ChainOfCustody");

                    b.Navigation("ProcessedVersions");
                });

            modelBuilder.Entity("IIM.Shared.Models.Workspace", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Sessions");

                    b.Navigation("TimelineEvents");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
