using System.Collections.Generic;
using IIM.Shared.Dtos;

namespace IIM.Shared.Models
{
	/// <summary>
	/// Configuration container for system model templates.
	/// This directly maps to the "ModelTemplates" section of appsettings.json,
	/// which is generated by the CAILE installer.
	/// </summary>
	public class ModelTemplatesConfig
	{
		/// <summary>
		/// Determines which system template should be used by default.
		/// Installer sets this to the chosen tier (micro / mini / small).
		/// ModelTemplateService may override it with a database value if one exists.
		/// </summary>
		public string ActiveTemplateId { get; set; } = "mini";

		/// <summary>
		/// The local or remote Foundry endpoint used to resolve model IDs
		/// into actual Foundry-serving endpoints for inference.
		/// The installer injects this automatically.
		/// </summary>
		public string FoundryEndpoint { get; set; } = string.Empty;

		/// <summary>
		/// Dictionary of available system templates.
		/// Keys are template IDs (micro, mini, small, etc.).
		/// Values are template definitions consumed by the template system.
		/// These are returned to the API and UI as ModelTemplateDto objects.
		/// </summary>
		public Dictionary<string, ModelTemplateDto> Templates { get; set; } = new();
	}
}
