using Microsoft.FluentUI.AspNetCore.Components;
using System.Text;




/// <summary>
/// Represents the icons used by <see cref="FluentCxFileManager{TItem}"/>.
/// </summary>
public static partial class FileIcons
{
    /// <summary>
    /// Represents the icons for the details panel.
    /// </summary>
    private static readonly Dictionary<string, Icon> _iconForDetailsPanel = new()
    {
        [".xls"] = new Size128.ExcelIcon(),
        [".xlsx"] = new Size128.ExcelIcon(),
        [".xlsm"] = new Size128.ExcelIcon(),
        [".xlsb"] = new Size128.ExcelIcon(),
        [".xlam"] = new Size128.ExcelIcon(),
        [".xltx"] = new Size128.ExcelIcon(),
        [".xltm"] = new Size128.ExcelIcon(),
        [".xla"] = new Size128.ExcelIcon(),
        [".xlm"] = new Size128.ExcelIcon(),
        [".xlw"] = new Size128.ExcelIcon(),
        [".odc"] = new Size128.ExcelIcon(),
        [".ods"] = new Size128.ExcelIcon(),
        [".csv"] = new Size128.ExcelIcon(),

        [".pptx"] = new Size128.PowerpointIcon(),
        [".pptm"] = new Size128.PowerpointIcon(),
        [".ppt"] = new Size128.PowerpointIcon(),
        [".potx"] = new Size128.PowerpointIcon(),
        [".potm"] = new Size128.PowerpointIcon(),
        [".pot"] = new Size128.PowerpointIcon(),
        [".ppsx"] = new Size128.PowerpointIcon(),
        [".ppsm"] = new Size128.PowerpointIcon(),
        [".pps"] = new Size128.PowerpointIcon(),
        [".ppam"] = new Size128.PowerpointIcon(),
        [".ppa"] = new Size128.PowerpointIcon(),
        [".odp"] = new Size128.PowerpointIcon(),

        [".docx"] = new Size128.WordIcon(),
        [".doc"] = new Size128.WordIcon(),
        [".docm"] = new Size128.WordIcon(),
        [".dotx"] = new Size128.WordIcon(),
        [".dotm"] = new Size128.WordIcon(),
        [".dot"] = new Size128.WordIcon(),
        [".rtf"] = new Size128.WordIcon(),
        [".odt"] = new Size128.WordIcon(),

        [".jpg"] = new Size128.ImageIcon(),
        [".jpeg"] = new Size128.ImageIcon(),
        [".jfif"] = new Size128.ImageIcon(),
        [".pjpeg"] = new Size128.ImageIcon(),
        [".pjpg"] = new Size128.ImageIcon(),
        [".png"] = new Size128.ImageIcon(),
        [".bmp"] = new Size128.ImageIcon(),
        [".apng"] = new Size128.ImageIcon(),
        [".avif"] = new Size128.ImageIcon(),
        [".gif"] = new Size128.ImageIcon(),
        [".svg"] = new Size128.ImageIcon(),
        [".webp"] = new Size128.ImageIcon(),
        [".ico"] = new Size128.ImageIcon(),
        [".cur"] = new Size128.ImageIcon(),
        [".tif"] = new Size128.ImageIcon(),
        [".tiff"] = new Size128.ImageIcon(),

        [".3gp"] = new Size128.MusicIcon(),
        [".aa"] = new Size128.MusicIcon(),
        [".aac"] = new Size128.MusicIcon(),
        [".aax"] = new Size128.MusicIcon(),
        [".act"] = new Size128.MusicIcon(),
        [".aiff"] = new Size128.MusicIcon(),
        [".alac"] = new Size128.MusicIcon(),
        [".amr"] = new Size128.MusicIcon(),
        [".ape"] = new Size128.MusicIcon(),
        [".au"] = new Size128.MusicIcon(),
        [".awb"] = new Size128.MusicIcon(),
        [".dss"] = new Size128.MusicIcon(),
        [".dvf"] = new Size128.MusicIcon(),
        [".flac"] = new Size128.MusicIcon(),
        [".gsm"] = new Size128.MusicIcon(),
        [".iklax"] = new Size128.MusicIcon(),
        [".ivs"] = new Size128.MusicIcon(),
        [".m4a"] = new Size128.MusicIcon(),
        [".m4b"] = new Size128.MusicIcon(),
        [".m4p"] = new Size128.MusicIcon(),
        [".mmf"] = new Size128.MusicIcon(),
        [".movpkg"] = new Size128.MusicIcon(),
        [".mp1"] = new Size128.MusicIcon(),
        [".mp2"] = new Size128.MusicIcon(),
        [".mp3"] = new Size128.MusicIcon(),
        [".mpc"] = new Size128.MusicIcon(),
        [".msv"] = new Size128.MusicIcon(),
        [".nmf"] = new Size128.MusicIcon(),
        [".ogg"] = new Size128.MusicIcon(),
        [".oga"] = new Size128.MusicIcon(),
        [".mogg"] = new Size128.MusicIcon(),
        [".opus"] = new Size128.MusicIcon(),
        [".ra"] = new Size128.MusicIcon(),
        [".rm"] = new Size128.MusicIcon(),
        [".raw"] = new Size128.MusicIcon(),
        [".rf64"] = new Size128.MusicIcon(),
        [".tta"] = new Size128.MusicIcon(),
        [".voc"] = new Size128.MusicIcon(),
        [".vox"] = new Size128.MusicIcon(),
        [".wav"] = new Size128.MusicIcon(),
        [".wma"] = new Size128.MusicIcon(),
        [".wv"] = new Size128.MusicIcon(),
        [".webm"] = new Size128.MusicIcon(),
        [".8svx"] = new Size128.MusicIcon(),
        [".cda"] = new Size128.MusicIcon(),

        [".webm"] = new Size128.VideoIcon(),
        [".mkv"] = new Size128.VideoIcon(),
        [".flv"] = new Size128.VideoIcon(),
        [".vob"] = new Size128.VideoIcon(),
        [".ogv"] = new Size128.VideoIcon(),
        [".drc"] = new Size128.VideoIcon(),
        [".gifv"] = new Size128.VideoIcon(),
        [".avi"] = new Size128.VideoIcon(),
        [".mts"] = new Size128.VideoIcon(),
        [".m2ts"] = new Size128.VideoIcon(),
        [".ts"] = new Size128.VideoIcon(),
        [".mov"] = new Size128.VideoIcon(),
        [".qt"] = new Size128.VideoIcon(),
        [".wmv"] = new Size128.VideoIcon(),
        [".yuv"] = new Size128.VideoIcon(),
        [".rmvb"] = new Size128.VideoIcon(),
        [".viv"] = new Size128.VideoIcon(),
        [".asf"] = new Size128.VideoIcon(),
        [".amv"] = new Size128.VideoIcon(),
        [".mp4"] = new Size128.VideoIcon(),
        [".m4p"] = new Size128.VideoIcon(),
        [".m4v"] = new Size128.VideoIcon(),
        [".mpv"] = new Size128.VideoIcon(),
        [".svi"] = new Size128.VideoIcon(),
        [".3g2"] = new Size128.VideoIcon(),
        [".mxf"] = new Size128.VideoIcon(),
        [".roq"] = new Size128.VideoIcon(),
        [".nsv"] = new Size128.VideoIcon(),

        [".pdf"] = new Size128.PdfIcon(),

        [".json"] = new Size128.JsonIcon(),

        [".pbix"] = new Size128.PowerBiIcon(),

        [".exe"] = new Size128.ProgramIcon(),

        ["Default"] = new Size128.DefaultFileIcon(),
    };

    /// <summary>
    /// Represents the icons from extensions.
    /// </summary>
    private static readonly Dictionary<string, Icon> _iconsFromExtension = new()
    {
        [".xls"] = new Size32.ExcelIcon(),
        [".xlsx"] = new Size32.ExcelIcon(),
        [".xlsm"] = new Size32.ExcelIcon(),
        [".xlsb"] = new Size32.ExcelIcon(),
        [".xlam"] = new Size32.ExcelIcon(),
        [".xltx"] = new Size32.ExcelIcon(),
        [".xltm"] = new Size32.ExcelIcon(),
        [".xla"] = new Size32.ExcelIcon(),
        [".xlm"] = new Size32.ExcelIcon(),
        [".xlw"] = new Size32.ExcelIcon(),
        [".odc"] = new Size32.ExcelIcon(),
        [".ods"] = new Size32.ExcelIcon(),
        [".csv"] = new Size32.ExcelIcon(),

        [".pptx"] = new Size32.PowerpointIcon(),
        [".pptm"] = new Size32.PowerpointIcon(),
        [".ppt"] = new Size32.PowerpointIcon(),
        [".potx"] = new Size32.PowerpointIcon(),
        [".potm"] = new Size32.PowerpointIcon(),
        [".pot"] = new Size32.PowerpointIcon(),
        [".ppsx"] = new Size32.PowerpointIcon(),
        [".ppsm"] = new Size32.PowerpointIcon(),
        [".pps"] = new Size32.PowerpointIcon(),
        [".ppam"] = new Size32.PowerpointIcon(),
        [".ppa"] = new Size32.PowerpointIcon(),
        [".odp"] = new Size32.PowerpointIcon(),

        [".docx"] = new Size32.WordIcon(),
        [".doc"] = new Size32.WordIcon(),
        [".docm"] = new Size32.WordIcon(),
        [".dotx"] = new Size32.WordIcon(),
        [".dotm"] = new Size32.WordIcon(),
        [".dot"] = new Size32.WordIcon(),
        [".rtf"] = new Size32.WordIcon(),
        [".odt"] = new Size32.WordIcon(),

        [".jpg"] = new Size32.ImageIcon(),
        [".jpeg"] = new Size32.ImageIcon(),
        [".jfif"] = new Size32.ImageIcon(),
        [".pjpeg"] = new Size32.ImageIcon(),
        [".pjpg"] = new Size32.ImageIcon(),
        [".png"] = new Size32.ImageIcon(),
        [".bmp"] = new Size32.ImageIcon(),
        [".apng"] = new Size32.ImageIcon(),
        [".avif"] = new Size32.ImageIcon(),
        [".gif"] = new Size32.ImageIcon(),
        [".svg"] = new Size32.ImageIcon(),
        [".webp"] = new Size32.ImageIcon(),
        [".ico"] = new Size32.ImageIcon(),
        [".cur"] = new Size32.ImageIcon(),
        [".tif"] = new Size32.ImageIcon(),
        [".tiff"] = new Size32.ImageIcon(),

        [".3gp"] = new Size32.MusicIcon(),
        [".aa"] = new Size32.MusicIcon(),
        [".aac"] = new Size32.MusicIcon(),
        [".aax"] = new Size32.MusicIcon(),
        [".act"] = new Size32.MusicIcon(),
        [".aiff"] = new Size32.MusicIcon(),
        [".alac"] = new Size32.MusicIcon(),
        [".amr"] = new Size32.MusicIcon(),
        [".ape"] = new Size32.MusicIcon(),
        [".au"] = new Size32.MusicIcon(),
        [".awb"] = new Size32.MusicIcon(),
        [".dss"] = new Size32.MusicIcon(),
        [".dvf"] = new Size32.MusicIcon(),
        [".flac"] = new Size32.MusicIcon(),
        [".gsm"] = new Size32.MusicIcon(),
        [".iklax"] = new Size32.MusicIcon(),
        [".ivs"] = new Size32.MusicIcon(),
        [".m4a"] = new Size32.MusicIcon(),
        [".m4b"] = new Size32.MusicIcon(),
        [".m4p"] = new Size32.MusicIcon(),
        [".mmf"] = new Size32.MusicIcon(),
        [".movpkg"] = new Size32.MusicIcon(),
        [".mp1"] = new Size32.MusicIcon(),
        [".mp2"] = new Size32.MusicIcon(),
        [".mp3"] = new Size32.MusicIcon(),
        [".mpc"] = new Size32.MusicIcon(),
        [".msv"] = new Size32.MusicIcon(),
        [".nmf"] = new Size32.MusicIcon(),
        [".ogg"] = new Size32.MusicIcon(),
        [".oga"] = new Size32.MusicIcon(),
        [".mogg"] = new Size32.MusicIcon(),
        [".opus"] = new Size32.MusicIcon(),
        [".ra"] = new Size32.MusicIcon(),
        [".rm"] = new Size32.MusicIcon(),
        [".raw"] = new Size32.MusicIcon(),
        [".rf64"] = new Size32.MusicIcon(),
        [".tta"] = new Size32.MusicIcon(),
        [".voc"] = new Size32.MusicIcon(),
        [".vox"] = new Size32.MusicIcon(),
        [".wav"] = new Size32.MusicIcon(),
        [".wma"] = new Size32.MusicIcon(),
        [".wv"] = new Size32.MusicIcon(),
        [".webm"] = new Size32.MusicIcon(),
        [".8svx"] = new Size32.MusicIcon(),
        [".cda"] = new Size32.MusicIcon(),

        [".webm"] = new Size32.VideoIcon(),
        [".mkv"] = new Size32.VideoIcon(),
        [".flv"] = new Size32.VideoIcon(),
        [".vob"] = new Size32.VideoIcon(),
        [".ogv"] = new Size32.VideoIcon(),
        [".drc"] = new Size32.VideoIcon(),
        [".gifv"] = new Size32.VideoIcon(),
        [".avi"] = new Size32.VideoIcon(),
        [".mts"] = new Size32.VideoIcon(),
        [".m2ts"] = new Size32.VideoIcon(),
        [".ts"] = new Size32.VideoIcon(),
        [".mov"] = new Size32.VideoIcon(),
        [".qt"] = new Size32.VideoIcon(),
        [".wmv"] = new Size32.VideoIcon(),
        [".yuv"] = new Size32.VideoIcon(),
        [".rmvb"] = new Size32.VideoIcon(),
        [".viv"] = new Size32.VideoIcon(),
        [".asf"] = new Size32.VideoIcon(),
        [".amv"] = new Size32.VideoIcon(),
        [".mp4"] = new Size32.VideoIcon(),
        [".m4p"] = new Size32.VideoIcon(),
        [".m4v"] = new Size32.VideoIcon(),
        [".mpv"] = new Size32.VideoIcon(),
        [".svi"] = new Size32.VideoIcon(),
        [".3g2"] = new Size32.VideoIcon(),
        [".mxf"] = new Size32.VideoIcon(),
        [".roq"] = new Size32.VideoIcon(),
        [".nsv"] = new Size32.VideoIcon(),

        [".pbix"] = new Size32.PowerBiIcon(),

        [".pdf"] = new Size32.PdfIcon(),
        [".json"] = new Size32.JsonIcon(),
        [".exe"] = new Size32.ProgramIcon(),

        ["Default"] = new Size32.DefaultFileIcon(),
    };

    /// <summary>
    /// Represents the icons used for the <see cref="FluentCxFileManager{TItem}"/> from its <see cref="FileView"/> parameter. 
    /// </summary>
    private static readonly Dictionary<FileView, Dictionary<string, Icon>> _sizedGridOptionsIconFromExtensions = new(EqualityComparer<FileView>.Default)
    {
        [FileView.Mosaic] = new()
        {
            [".xls"] = new Size32.ExcelIcon(),
            [".xlsx"] = new Size32.ExcelIcon(),
            [".xlsm"] = new Size32.ExcelIcon(),
            [".xlsb"] = new Size32.ExcelIcon(),
            [".xlam"] = new Size32.ExcelIcon(),
            [".xltx"] = new Size32.ExcelIcon(),
            [".xltm"] = new Size32.ExcelIcon(),
            [".xla"] = new Size32.ExcelIcon(),
            [".xlm"] = new Size32.ExcelIcon(),
            [".xlw"] = new Size32.ExcelIcon(),
            [".odc"] = new Size32.ExcelIcon(),
            [".ods"] = new Size32.ExcelIcon(),
            [".csv"] = new Size32.ExcelIcon(),

            [".pptx"] = new Size32.PowerpointIcon(),
            [".pptm"] = new Size32.PowerpointIcon(),
            [".ppt"] = new Size32.PowerpointIcon(),
            [".potx"] = new Size32.PowerpointIcon(),
            [".potm"] = new Size32.PowerpointIcon(),
            [".pot"] = new Size32.PowerpointIcon(),
            [".ppsx"] = new Size32.PowerpointIcon(),
            [".ppsm"] = new Size32.PowerpointIcon(),
            [".pps"] = new Size32.PowerpointIcon(),
            [".ppam"] = new Size32.PowerpointIcon(),
            [".ppa"] = new Size32.PowerpointIcon(),
            [".odp"] = new Size32.PowerpointIcon(),

            [".docx"] = new Size32.WordIcon(),
            [".doc"] = new Size32.WordIcon(),
            [".docm"] = new Size32.WordIcon(),
            [".dotx"] = new Size32.WordIcon(),
            [".dotm"] = new Size32.WordIcon(),
            [".dot"] = new Size32.WordIcon(),
            [".rtf"] = new Size32.WordIcon(),
            [".odt"] = new Size32.WordIcon(),

            [".jpg"] = new Size32.ImageIcon(),
            [".jpeg"] = new Size32.ImageIcon(),
            [".jfif"] = new Size32.ImageIcon(),
            [".pjpeg"] = new Size32.ImageIcon(),
            [".pjpg"] = new Size32.ImageIcon(),
            [".png"] = new Size32.ImageIcon(),
            [".bmp"] = new Size32.ImageIcon(),
            [".apng"] = new Size32.ImageIcon(),
            [".avif"] = new Size32.ImageIcon(),
            [".gif"] = new Size32.ImageIcon(),
            [".svg"] = new Size32.ImageIcon(),
            [".webp"] = new Size32.ImageIcon(),
            [".ico"] = new Size32.ImageIcon(),
            [".cur"] = new Size32.ImageIcon(),
            [".tif"] = new Size32.ImageIcon(),
            [".tiff"] = new Size32.ImageIcon(),

            [".3gp"] = new Size32.MusicIcon(),
            [".aa"] = new Size32.MusicIcon(),
            [".aac"] = new Size32.MusicIcon(),
            [".aax"] = new Size32.MusicIcon(),
            [".act"] = new Size32.MusicIcon(),
            [".aiff"] = new Size32.MusicIcon(),
            [".alac"] = new Size32.MusicIcon(),
            [".amr"] = new Size32.MusicIcon(),
            [".ape"] = new Size32.MusicIcon(),
            [".au"] = new Size32.MusicIcon(),
            [".awb"] = new Size32.MusicIcon(),
            [".dss"] = new Size32.MusicIcon(),
            [".dvf"] = new Size32.MusicIcon(),
            [".flac"] = new Size32.MusicIcon(),
            [".gsm"] = new Size32.MusicIcon(),
            [".iklax"] = new Size32.MusicIcon(),
            [".ivs"] = new Size32.MusicIcon(),
            [".m4a"] = new Size32.MusicIcon(),
            [".m4b"] = new Size32.MusicIcon(),
            [".m4p"] = new Size32.MusicIcon(),
            [".mmf"] = new Size32.MusicIcon(),
            [".movpkg"] = new Size32.MusicIcon(),
            [".mp1"] = new Size32.MusicIcon(),
            [".mp2"] = new Size32.MusicIcon(),
            [".mp3"] = new Size32.MusicIcon(),
            [".mpc"] = new Size32.MusicIcon(),
            [".msv"] = new Size32.MusicIcon(),
            [".nmf"] = new Size32.MusicIcon(),
            [".ogg"] = new Size32.MusicIcon(),
            [".oga"] = new Size32.MusicIcon(),
            [".mogg"] = new Size32.MusicIcon(),
            [".opus"] = new Size32.MusicIcon(),
            [".ra"] = new Size32.MusicIcon(),
            [".rm"] = new Size32.MusicIcon(),
            [".raw"] = new Size32.MusicIcon(),
            [".rf64"] = new Size32.MusicIcon(),
            [".tta"] = new Size32.MusicIcon(),
            [".voc"] = new Size32.MusicIcon(),
            [".vox"] = new Size32.MusicIcon(),
            [".wav"] = new Size32.MusicIcon(),
            [".wma"] = new Size32.MusicIcon(),
            [".wv"] = new Size32.MusicIcon(),
            [".webm"] = new Size32.MusicIcon(),
            [".8svx"] = new Size32.MusicIcon(),
            [".cda"] = new Size32.MusicIcon(),

            [".webm"] = new Size32.VideoIcon(),
            [".mkv"] = new Size32.VideoIcon(),
            [".flv"] = new Size32.VideoIcon(),
            [".vob"] = new Size32.VideoIcon(),
            [".ogv"] = new Size32.VideoIcon(),
            [".drc"] = new Size32.VideoIcon(),
            [".gifv"] = new Size32.VideoIcon(),
            [".avi"] = new Size32.VideoIcon(),
            [".mts"] = new Size32.VideoIcon(),
            [".m2ts"] = new Size32.VideoIcon(),
            [".ts"] = new Size32.VideoIcon(),
            [".mov"] = new Size32.VideoIcon(),
            [".qt"] = new Size32.VideoIcon(),
            [".wmv"] = new Size32.VideoIcon(),
            [".yuv"] = new Size32.VideoIcon(),
            [".rmvb"] = new Size32.VideoIcon(),
            [".viv"] = new Size32.VideoIcon(),
            [".asf"] = new Size32.VideoIcon(),
            [".amv"] = new Size32.VideoIcon(),
            [".mp4"] = new Size32.VideoIcon(),
            [".m4p"] = new Size32.VideoIcon(),
            [".m4v"] = new Size32.VideoIcon(),
            [".mpv"] = new Size32.VideoIcon(),
            [".svi"] = new Size32.VideoIcon(),
            [".3g2"] = new Size32.VideoIcon(),
            [".mxf"] = new Size32.VideoIcon(),
            [".roq"] = new Size32.VideoIcon(),
            [".nsv"] = new Size32.VideoIcon(),

            [".pbix"] = new Size32.PowerBiIcon(),

            [".pdf"] = new Size32.PdfIcon(),
            [".json"] = new Size32.JsonIcon(),
            [".exe"] = new Size32.ProgramIcon(),

            ["Default"] = new Size32.DefaultFileIcon(),
            ["Folder"] = new Size32.FolderIcon()
        },

        [FileView.SmallIcons] = new()
        {
            [".xls"] = new Size24.ExcelIcon(),
            [".xlsx"] = new Size24.ExcelIcon(),
            [".xlsm"] = new Size24.ExcelIcon(),
            [".xlsb"] = new Size24.ExcelIcon(),
            [".xlam"] = new Size24.ExcelIcon(),
            [".xltx"] = new Size24.ExcelIcon(),
            [".xltm"] = new Size24.ExcelIcon(),
            [".xla"] = new Size24.ExcelIcon(),
            [".xlm"] = new Size24.ExcelIcon(),
            [".xlw"] = new Size24.ExcelIcon(),
            [".odc"] = new Size24.ExcelIcon(),
            [".ods"] = new Size24.ExcelIcon(),
            [".csv"] = new Size24.ExcelIcon(),

            [".pptx"] = new Size24.PowerpointIcon(),
            [".pptm"] = new Size24.PowerpointIcon(),
            [".ppt"] = new Size24.PowerpointIcon(),
            [".potx"] = new Size24.PowerpointIcon(),
            [".potm"] = new Size24.PowerpointIcon(),
            [".pot"] = new Size24.PowerpointIcon(),
            [".ppsx"] = new Size24.PowerpointIcon(),
            [".ppsm"] = new Size24.PowerpointIcon(),
            [".pps"] = new Size24.PowerpointIcon(),
            [".ppam"] = new Size24.PowerpointIcon(),
            [".ppa"] = new Size24.PowerpointIcon(),
            [".odp"] = new Size24.PowerpointIcon(),

            [".docx"] = new Size24.WordIcon(),
            [".doc"] = new Size24.WordIcon(),
            [".docm"] = new Size24.WordIcon(),
            [".dotx"] = new Size24.WordIcon(),
            [".dotm"] = new Size24.WordIcon(),
            [".dot"] = new Size24.WordIcon(),
            [".rtf"] = new Size24.WordIcon(),
            [".odt"] = new Size24.WordIcon(),

            [".jpg"] = new Size24.ImageIcon(),
            [".jpeg"] = new Size24.ImageIcon(),
            [".jfif"] = new Size24.ImageIcon(),
            [".pjpeg"] = new Size24.ImageIcon(),
            [".pjpg"] = new Size24.ImageIcon(),
            [".png"] = new Size24.ImageIcon(),
            [".bmp"] = new Size24.ImageIcon(),
            [".apng"] = new Size24.ImageIcon(),
            [".avif"] = new Size24.ImageIcon(),
            [".gif"] = new Size24.ImageIcon(),
            [".svg"] = new Size24.ImageIcon(),
            [".webp"] = new Size24.ImageIcon(),
            [".ico"] = new Size24.ImageIcon(),
            [".cur"] = new Size24.ImageIcon(),
            [".tif"] = new Size24.ImageIcon(),
            [".tiff"] = new Size24.ImageIcon(),

            [".3gp"] = new Size24.MusicIcon(),
            [".aa"] = new Size24.MusicIcon(),
            [".aac"] = new Size24.MusicIcon(),
            [".aax"] = new Size24.MusicIcon(),
            [".act"] = new Size24.MusicIcon(),
            [".aiff"] = new Size24.MusicIcon(),
            [".alac"] = new Size24.MusicIcon(),
            [".amr"] = new Size24.MusicIcon(),
            [".ape"] = new Size24.MusicIcon(),
            [".au"] = new Size24.MusicIcon(),
            [".awb"] = new Size24.MusicIcon(),
            [".dss"] = new Size24.MusicIcon(),
            [".dvf"] = new Size24.MusicIcon(),
            [".flac"] = new Size24.MusicIcon(),
            [".gsm"] = new Size24.MusicIcon(),
            [".iklax"] = new Size24.MusicIcon(),
            [".ivs"] = new Size24.MusicIcon(),
            [".m4a"] = new Size24.MusicIcon(),
            [".m4b"] = new Size24.MusicIcon(),
            [".m4p"] = new Size24.MusicIcon(),
            [".mmf"] = new Size24.MusicIcon(),
            [".movpkg"] = new Size24.MusicIcon(),
            [".mp1"] = new Size24.MusicIcon(),
            [".mp2"] = new Size24.MusicIcon(),
            [".mp3"] = new Size24.MusicIcon(),
            [".mpc"] = new Size24.MusicIcon(),
            [".msv"] = new Size24.MusicIcon(),
            [".nmf"] = new Size24.MusicIcon(),
            [".ogg"] = new Size24.MusicIcon(),
            [".oga"] = new Size24.MusicIcon(),
            [".mogg"] = new Size24.MusicIcon(),
            [".opus"] = new Size24.MusicIcon(),
            [".ra"] = new Size24.MusicIcon(),
            [".rm"] = new Size24.MusicIcon(),
            [".raw"] = new Size24.MusicIcon(),
            [".rf64"] = new Size24.MusicIcon(),
            [".tta"] = new Size24.MusicIcon(),
            [".voc"] = new Size24.MusicIcon(),
            [".vox"] = new Size24.MusicIcon(),
            [".wav"] = new Size24.MusicIcon(),
            [".wma"] = new Size24.MusicIcon(),
            [".wv"] = new Size24.MusicIcon(),
            [".webm"] = new Size24.MusicIcon(),
            [".8svx"] = new Size24.MusicIcon(),
            [".cda"] = new Size24.MusicIcon(),

            [".webm"] = new Size24.VideoIcon(),
            [".mkv"] = new Size24.VideoIcon(),
            [".flv"] = new Size24.VideoIcon(),
            [".vob"] = new Size24.VideoIcon(),
            [".ogv"] = new Size24.VideoIcon(),
            [".drc"] = new Size24.VideoIcon(),
            [".gifv"] = new Size24.VideoIcon(),
            [".avi"] = new Size24.VideoIcon(),
            [".mts"] = new Size24.VideoIcon(),
            [".m2ts"] = new Size24.VideoIcon(),
            [".ts"] = new Size24.VideoIcon(),
            [".mov"] = new Size24.VideoIcon(),
            [".qt"] = new Size24.VideoIcon(),
            [".wmv"] = new Size24.VideoIcon(),
            [".yuv"] = new Size24.VideoIcon(),
            [".rmvb"] = new Size24.VideoIcon(),
            [".viv"] = new Size24.VideoIcon(),
            [".asf"] = new Size24.VideoIcon(),
            [".amv"] = new Size24.VideoIcon(),
            [".mp4"] = new Size24.VideoIcon(),
            [".m4p"] = new Size24.VideoIcon(),
            [".m4v"] = new Size24.VideoIcon(),
            [".mpv"] = new Size24.VideoIcon(),
            [".svi"] = new Size24.VideoIcon(),
            [".3g2"] = new Size24.VideoIcon(),
            [".mxf"] = new Size24.VideoIcon(),
            [".roq"] = new Size24.VideoIcon(),
            [".nsv"] = new Size24.VideoIcon(),

            [".pbix"] = new Size24.PowerBiIcon(),

            [".pdf"] = new Size24.PdfIcon(),
            [".json"] = new Size24.JsonIcon(),
            [".exe"] = new Size24.ProgramIcon(),

            ["Default"] = new Size24.DefaultFileIcon(),
            ["Folder"] = new Size24.FolderIcon()
        },

        [FileView.MediumIcons] = new()
        {
            [".xls"] = new Size72.ExcelIcon(),
            [".xlsx"] = new Size72.ExcelIcon(),
            [".xlsm"] = new Size72.ExcelIcon(),
            [".xlsb"] = new Size72.ExcelIcon(),
            [".xlam"] = new Size72.ExcelIcon(),
            [".xltx"] = new Size72.ExcelIcon(),
            [".xltm"] = new Size72.ExcelIcon(),
            [".xla"] = new Size72.ExcelIcon(),
            [".xlm"] = new Size72.ExcelIcon(),
            [".xlw"] = new Size72.ExcelIcon(),
            [".odc"] = new Size72.ExcelIcon(),
            [".ods"] = new Size72.ExcelIcon(),
            [".csv"] = new Size72.ExcelIcon(),

            [".pptx"] = new Size72.PowerpointIcon(),
            [".pptm"] = new Size72.PowerpointIcon(),
            [".ppt"] = new Size72.PowerpointIcon(),
            [".potx"] = new Size72.PowerpointIcon(),
            [".potm"] = new Size72.PowerpointIcon(),
            [".pot"] = new Size72.PowerpointIcon(),
            [".ppsx"] = new Size72.PowerpointIcon(),
            [".ppsm"] = new Size72.PowerpointIcon(),
            [".pps"] = new Size72.PowerpointIcon(),
            [".ppam"] = new Size72.PowerpointIcon(),
            [".ppa"] = new Size72.PowerpointIcon(),
            [".odp"] = new Size72.PowerpointIcon(),

            [".docx"] = new Size72.WordIcon(),
            [".doc"] = new Size72.WordIcon(),
            [".docm"] = new Size72.WordIcon(),
            [".dotx"] = new Size72.WordIcon(),
            [".dotm"] = new Size72.WordIcon(),
            [".dot"] = new Size72.WordIcon(),
            [".rtf"] = new Size72.WordIcon(),
            [".odt"] = new Size72.WordIcon(),

            [".jpg"] = new Size72.ImageIcon(),
            [".jpeg"] = new Size72.ImageIcon(),
            [".jfif"] = new Size72.ImageIcon(),
            [".pjpeg"] = new Size72.ImageIcon(),
            [".pjpg"] = new Size72.ImageIcon(),
            [".png"] = new Size72.ImageIcon(),
            [".bmp"] = new Size72.ImageIcon(),
            [".apng"] = new Size72.ImageIcon(),
            [".avif"] = new Size72.ImageIcon(),
            [".gif"] = new Size72.ImageIcon(),
            [".svg"] = new Size72.ImageIcon(),
            [".webp"] = new Size72.ImageIcon(),
            [".ico"] = new Size72.ImageIcon(),
            [".cur"] = new Size72.ImageIcon(),
            [".tif"] = new Size72.ImageIcon(),
            [".tiff"] = new Size72.ImageIcon(),

            [".3gp"] = new Size72.MusicIcon(),
            [".aa"] = new Size72.MusicIcon(),
            [".aac"] = new Size72.MusicIcon(),
            [".aax"] = new Size72.MusicIcon(),
            [".act"] = new Size72.MusicIcon(),
            [".aiff"] = new Size72.MusicIcon(),
            [".alac"] = new Size72.MusicIcon(),
            [".amr"] = new Size72.MusicIcon(),
            [".ape"] = new Size72.MusicIcon(),
            [".au"] = new Size72.MusicIcon(),
            [".awb"] = new Size72.MusicIcon(),
            [".dss"] = new Size72.MusicIcon(),
            [".dvf"] = new Size72.MusicIcon(),
            [".flac"] = new Size72.MusicIcon(),
            [".gsm"] = new Size72.MusicIcon(),
            [".iklax"] = new Size72.MusicIcon(),
            [".ivs"] = new Size72.MusicIcon(),
            [".m4a"] = new Size72.MusicIcon(),
            [".m4b"] = new Size72.MusicIcon(),
            [".m4p"] = new Size72.MusicIcon(),
            [".mmf"] = new Size72.MusicIcon(),
            [".movpkg"] = new Size72.MusicIcon(),
            [".mp1"] = new Size72.MusicIcon(),
            [".mp2"] = new Size72.MusicIcon(),
            [".mp3"] = new Size72.MusicIcon(),
            [".mpc"] = new Size72.MusicIcon(),
            [".msv"] = new Size72.MusicIcon(),
            [".nmf"] = new Size72.MusicIcon(),
            [".ogg"] = new Size72.MusicIcon(),
            [".oga"] = new Size72.MusicIcon(),
            [".mogg"] = new Size72.MusicIcon(),
            [".opus"] = new Size72.MusicIcon(),
            [".ra"] = new Size72.MusicIcon(),
            [".rm"] = new Size72.MusicIcon(),
            [".raw"] = new Size72.MusicIcon(),
            [".rf64"] = new Size72.MusicIcon(),
            [".tta"] = new Size72.MusicIcon(),
            [".voc"] = new Size72.MusicIcon(),
            [".vox"] = new Size72.MusicIcon(),
            [".wav"] = new Size72.MusicIcon(),
            [".wma"] = new Size72.MusicIcon(),
            [".wv"] = new Size72.MusicIcon(),
            [".webm"] = new Size72.MusicIcon(),
            [".8svx"] = new Size72.MusicIcon(),
            [".cda"] = new Size72.MusicIcon(),

            [".webm"] = new Size72.VideoIcon(),
            [".mkv"] = new Size72.VideoIcon(),
            [".flv"] = new Size72.VideoIcon(),
            [".vob"] = new Size72.VideoIcon(),
            [".ogv"] = new Size72.VideoIcon(),
            [".drc"] = new Size72.VideoIcon(),
            [".gifv"] = new Size72.VideoIcon(),
            [".avi"] = new Size72.VideoIcon(),
            [".mts"] = new Size72.VideoIcon(),
            [".m2ts"] = new Size72.VideoIcon(),
            [".ts"] = new Size72.VideoIcon(),
            [".mov"] = new Size72.VideoIcon(),
            [".qt"] = new Size72.VideoIcon(),
            [".wmv"] = new Size72.VideoIcon(),
            [".yuv"] = new Size72.VideoIcon(),
            [".rmvb"] = new Size72.VideoIcon(),
            [".viv"] = new Size72.VideoIcon(),
            [".asf"] = new Size72.VideoIcon(),
            [".amv"] = new Size72.VideoIcon(),
            [".mp4"] = new Size72.VideoIcon(),
            [".m4p"] = new Size72.VideoIcon(),
            [".m4v"] = new Size72.VideoIcon(),
            [".mpv"] = new Size72.VideoIcon(),
            [".svi"] = new Size72.VideoIcon(),
            [".3g2"] = new Size72.VideoIcon(),
            [".mxf"] = new Size72.VideoIcon(),
            [".roq"] = new Size72.VideoIcon(),
            [".nsv"] = new Size72.VideoIcon(),

            [".pbix"] = new Size72.PowerBiIcon(),

            [".pdf"] = new Size72.PdfIcon(),
            [".json"] = new Size72.JsonIcon(),
            [".exe"] = new Size72.ProgramIcon(),

            ["Default"] = new Size72.DefaultFileIcon(),
            ["Folder"] = new Size72.FolderIcon()
        },

        [FileView.LargeIcons] = new()
        {
            [".xls"] = new Size96.ExcelIcon(),
            [".xlsx"] = new Size96.ExcelIcon(),
            [".xlsm"] = new Size96.ExcelIcon(),
            [".xlsb"] = new Size96.ExcelIcon(),
            [".xlam"] = new Size96.ExcelIcon(),
            [".xltx"] = new Size96.ExcelIcon(),
            [".xltm"] = new Size96.ExcelIcon(),
            [".xla"] = new Size96.ExcelIcon(),
            [".xlm"] = new Size96.ExcelIcon(),
            [".xlw"] = new Size96.ExcelIcon(),
            [".odc"] = new Size96.ExcelIcon(),
            [".ods"] = new Size96.ExcelIcon(),
            [".csv"] = new Size96.ExcelIcon(),

            [".pptx"] = new Size96.PowerpointIcon(),
            [".pptm"] = new Size96.PowerpointIcon(),
            [".ppt"] = new Size96.PowerpointIcon(),
            [".potx"] = new Size96.PowerpointIcon(),
            [".potm"] = new Size96.PowerpointIcon(),
            [".pot"] = new Size96.PowerpointIcon(),
            [".ppsx"] = new Size96.PowerpointIcon(),
            [".ppsm"] = new Size96.PowerpointIcon(),
            [".pps"] = new Size96.PowerpointIcon(),
            [".ppam"] = new Size96.PowerpointIcon(),
            [".ppa"] = new Size96.PowerpointIcon(),
            [".odp"] = new Size96.PowerpointIcon(),

            [".docx"] = new Size96.WordIcon(),
            [".doc"] = new Size96.WordIcon(),
            [".docm"] = new Size96.WordIcon(),
            [".dotx"] = new Size96.WordIcon(),
            [".dotm"] = new Size96.WordIcon(),
            [".dot"] = new Size96.WordIcon(),
            [".rtf"] = new Size96.WordIcon(),
            [".odt"] = new Size96.WordIcon(),

            [".jpg"] = new Size96.ImageIcon(),
            [".jpeg"] = new Size96.ImageIcon(),
            [".jfif"] = new Size96.ImageIcon(),
            [".pjpeg"] = new Size96.ImageIcon(),
            [".pjpg"] = new Size96.ImageIcon(),
            [".png"] = new Size96.ImageIcon(),
            [".bmp"] = new Size96.ImageIcon(),
            [".apng"] = new Size96.ImageIcon(),
            [".avif"] = new Size96.ImageIcon(),
            [".gif"] = new Size96.ImageIcon(),
            [".svg"] = new Size96.ImageIcon(),
            [".webp"] = new Size96.ImageIcon(),
            [".ico"] = new Size96.ImageIcon(),
            [".cur"] = new Size96.ImageIcon(),
            [".tif"] = new Size96.ImageIcon(),
            [".tiff"] = new Size96.ImageIcon(),

            [".3gp"] = new Size96.MusicIcon(),
            [".aa"] = new Size96.MusicIcon(),
            [".aac"] = new Size96.MusicIcon(),
            [".aax"] = new Size96.MusicIcon(),
            [".act"] = new Size96.MusicIcon(),
            [".aiff"] = new Size96.MusicIcon(),
            [".alac"] = new Size96.MusicIcon(),
            [".amr"] = new Size96.MusicIcon(),
            [".ape"] = new Size96.MusicIcon(),
            [".au"] = new Size96.MusicIcon(),
            [".awb"] = new Size96.MusicIcon(),
            [".dss"] = new Size96.MusicIcon(),
            [".dvf"] = new Size96.MusicIcon(),
            [".flac"] = new Size96.MusicIcon(),
            [".gsm"] = new Size96.MusicIcon(),
            [".iklax"] = new Size96.MusicIcon(),
            [".ivs"] = new Size96.MusicIcon(),
            [".m4a"] = new Size96.MusicIcon(),
            [".m4b"] = new Size96.MusicIcon(),
            [".m4p"] = new Size96.MusicIcon(),
            [".mmf"] = new Size96.MusicIcon(),
            [".movpkg"] = new Size96.MusicIcon(),
            [".mp1"] = new Size96.MusicIcon(),
            [".mp2"] = new Size96.MusicIcon(),
            [".mp3"] = new Size96.MusicIcon(),
            [".mpc"] = new Size96.MusicIcon(),
            [".msv"] = new Size96.MusicIcon(),
            [".nmf"] = new Size96.MusicIcon(),
            [".ogg"] = new Size96.MusicIcon(),
            [".oga"] = new Size96.MusicIcon(),
            [".mogg"] = new Size96.MusicIcon(),
            [".opus"] = new Size96.MusicIcon(),
            [".ra"] = new Size96.MusicIcon(),
            [".rm"] = new Size96.MusicIcon(),
            [".raw"] = new Size96.MusicIcon(),
            [".rf64"] = new Size96.MusicIcon(),
            [".tta"] = new Size96.MusicIcon(),
            [".voc"] = new Size96.MusicIcon(),
            [".vox"] = new Size96.MusicIcon(),
            [".wav"] = new Size96.MusicIcon(),
            [".wma"] = new Size96.MusicIcon(),
            [".wv"] = new Size96.MusicIcon(),
            [".webm"] = new Size96.MusicIcon(),
            [".8svx"] = new Size96.MusicIcon(),
            [".cda"] = new Size96.MusicIcon(),

            [".webm"] = new Size96.VideoIcon(),
            [".mkv"] = new Size96.VideoIcon(),
            [".flv"] = new Size96.VideoIcon(),
            [".vob"] = new Size96.VideoIcon(),
            [".ogv"] = new Size96.VideoIcon(),
            [".drc"] = new Size96.VideoIcon(),
            [".gifv"] = new Size96.VideoIcon(),
            [".avi"] = new Size96.VideoIcon(),
            [".mts"] = new Size96.VideoIcon(),
            [".m2ts"] = new Size96.VideoIcon(),
            [".ts"] = new Size96.VideoIcon(),
            [".mov"] = new Size96.VideoIcon(),
            [".qt"] = new Size96.VideoIcon(),
            [".wmv"] = new Size96.VideoIcon(),
            [".yuv"] = new Size96.VideoIcon(),
            [".rmvb"] = new Size96.VideoIcon(),
            [".viv"] = new Size96.VideoIcon(),
            [".asf"] = new Size96.VideoIcon(),
            [".amv"] = new Size96.VideoIcon(),
            [".mp4"] = new Size96.VideoIcon(),
            [".m4p"] = new Size96.VideoIcon(),
            [".m4v"] = new Size96.VideoIcon(),
            [".mpv"] = new Size96.VideoIcon(),
            [".svi"] = new Size96.VideoIcon(),
            [".3g2"] = new Size96.VideoIcon(),
            [".mxf"] = new Size96.VideoIcon(),
            [".roq"] = new Size96.VideoIcon(),
            [".nsv"] = new Size96.VideoIcon(),

            [".pbix"] = new Size96.PowerBiIcon(),

            [".pdf"] = new Size96.PdfIcon(),
            [".json"] = new Size96.JsonIcon(),
            [".exe"] = new Size96.ProgramIcon(),

            ["Default"] = new Size96.DefaultFileIcon(),
            ["Folder"] = new Size96.FolderIcon()
        },

        [FileView.VeryLargeIcons] = new()
        {
            [".xls"] = new Size128.ExcelIcon(),
            [".xlsx"] = new Size128.ExcelIcon(),
            [".xlsm"] = new Size128.ExcelIcon(),
            [".xlsb"] = new Size128.ExcelIcon(),
            [".xlam"] = new Size128.ExcelIcon(),
            [".xltx"] = new Size128.ExcelIcon(),
            [".xltm"] = new Size128.ExcelIcon(),
            [".xla"] = new Size128.ExcelIcon(),
            [".xlm"] = new Size128.ExcelIcon(),
            [".xlw"] = new Size128.ExcelIcon(),
            [".odc"] = new Size128.ExcelIcon(),
            [".ods"] = new Size128.ExcelIcon(),
            [".csv"] = new Size128.ExcelIcon(),

            [".pptx"] = new Size128.PowerpointIcon(),
            [".pptm"] = new Size128.PowerpointIcon(),
            [".ppt"] = new Size128.PowerpointIcon(),
            [".potx"] = new Size128.PowerpointIcon(),
            [".potm"] = new Size128.PowerpointIcon(),
            [".pot"] = new Size128.PowerpointIcon(),
            [".ppsx"] = new Size128.PowerpointIcon(),
            [".ppsm"] = new Size128.PowerpointIcon(),
            [".pps"] = new Size128.PowerpointIcon(),
            [".ppam"] = new Size128.PowerpointIcon(),
            [".ppa"] = new Size128.PowerpointIcon(),
            [".odp"] = new Size128.PowerpointIcon(),

            [".docx"] = new Size128.WordIcon(),
            [".doc"] = new Size128.WordIcon(),
            [".docm"] = new Size128.WordIcon(),
            [".dotx"] = new Size128.WordIcon(),
            [".dotm"] = new Size128.WordIcon(),
            [".dot"] = new Size128.WordIcon(),
            [".rtf"] = new Size128.WordIcon(),
            [".odt"] = new Size128.WordIcon(),

            [".jpg"] = new Size128.ImageIcon(),
            [".jpeg"] = new Size128.ImageIcon(),
            [".jfif"] = new Size128.ImageIcon(),
            [".pjpeg"] = new Size128.ImageIcon(),
            [".pjpg"] = new Size128.ImageIcon(),
            [".png"] = new Size128.ImageIcon(),
            [".bmp"] = new Size128.ImageIcon(),
            [".apng"] = new Size128.ImageIcon(),
            [".avif"] = new Size128.ImageIcon(),
            [".gif"] = new Size128.ImageIcon(),
            [".svg"] = new Size128.ImageIcon(),
            [".webp"] = new Size128.ImageIcon(),
            [".ico"] = new Size128.ImageIcon(),
            [".cur"] = new Size128.ImageIcon(),
            [".tif"] = new Size128.ImageIcon(),
            [".tiff"] = new Size128.ImageIcon(),

            [".3gp"] = new Size128.MusicIcon(),
            [".aa"] = new Size128.MusicIcon(),
            [".aac"] = new Size128.MusicIcon(),
            [".aax"] = new Size128.MusicIcon(),
            [".act"] = new Size128.MusicIcon(),
            [".aiff"] = new Size128.MusicIcon(),
            [".alac"] = new Size128.MusicIcon(),
            [".amr"] = new Size128.MusicIcon(),
            [".ape"] = new Size128.MusicIcon(),
            [".au"] = new Size128.MusicIcon(),
            [".awb"] = new Size128.MusicIcon(),
            [".dss"] = new Size128.MusicIcon(),
            [".dvf"] = new Size128.MusicIcon(),
            [".flac"] = new Size128.MusicIcon(),
            [".gsm"] = new Size128.MusicIcon(),
            [".iklax"] = new Size128.MusicIcon(),
            [".ivs"] = new Size128.MusicIcon(),
            [".m4a"] = new Size128.MusicIcon(),
            [".m4b"] = new Size128.MusicIcon(),
            [".m4p"] = new Size128.MusicIcon(),
            [".mmf"] = new Size128.MusicIcon(),
            [".movpkg"] = new Size128.MusicIcon(),
            [".mp1"] = new Size128.MusicIcon(),
            [".mp2"] = new Size128.MusicIcon(),
            [".mp3"] = new Size128.MusicIcon(),
            [".mpc"] = new Size128.MusicIcon(),
            [".msv"] = new Size128.MusicIcon(),
            [".nmf"] = new Size128.MusicIcon(),
            [".ogg"] = new Size128.MusicIcon(),
            [".oga"] = new Size128.MusicIcon(),
            [".mogg"] = new Size128.MusicIcon(),
            [".opus"] = new Size128.MusicIcon(),
            [".ra"] = new Size128.MusicIcon(),
            [".rm"] = new Size128.MusicIcon(),
            [".raw"] = new Size128.MusicIcon(),
            [".rf64"] = new Size128.MusicIcon(),
            [".tta"] = new Size128.MusicIcon(),
            [".voc"] = new Size128.MusicIcon(),
            [".vox"] = new Size128.MusicIcon(),
            [".wav"] = new Size128.MusicIcon(),
            [".wma"] = new Size128.MusicIcon(),
            [".wv"] = new Size128.MusicIcon(),
            [".webm"] = new Size128.MusicIcon(),
            [".8svx"] = new Size128.MusicIcon(),
            [".cda"] = new Size128.MusicIcon(),

            [".webm"] = new Size128.VideoIcon(),
            [".mkv"] = new Size128.VideoIcon(),
            [".flv"] = new Size128.VideoIcon(),
            [".vob"] = new Size128.VideoIcon(),
            [".ogv"] = new Size128.VideoIcon(),
            [".drc"] = new Size128.VideoIcon(),
            [".gifv"] = new Size128.VideoIcon(),
            [".avi"] = new Size128.VideoIcon(),
            [".mts"] = new Size128.VideoIcon(),
            [".m2ts"] = new Size128.VideoIcon(),
            [".ts"] = new Size128.VideoIcon(),
            [".mov"] = new Size128.VideoIcon(),
            [".qt"] = new Size128.VideoIcon(),
            [".wmv"] = new Size128.VideoIcon(),
            [".yuv"] = new Size128.VideoIcon(),
            [".rmvb"] = new Size128.VideoIcon(),
            [".viv"] = new Size128.VideoIcon(),
            [".asf"] = new Size128.VideoIcon(),
            [".amv"] = new Size128.VideoIcon(),
            [".mp4"] = new Size128.VideoIcon(),
            [".m4p"] = new Size128.VideoIcon(),
            [".m4v"] = new Size128.VideoIcon(),
            [".mpv"] = new Size128.VideoIcon(),
            [".svi"] = new Size128.VideoIcon(),
            [".3g2"] = new Size128.VideoIcon(),
            [".mxf"] = new Size128.VideoIcon(),
            [".roq"] = new Size128.VideoIcon(),
            [".nsv"] = new Size128.VideoIcon(),

            [".pbix"] = new Size128.PowerBiIcon(),

            [".pdf"] = new Size128.PdfIcon(),
            [".json"] = new Size128.JsonIcon(),
            [".exe"] = new Size128.ProgramIcon(),

            ["Default"] = new Size128.DefaultFileIcon(),
            ["Folder"] = new Size128.FolderIcon()
        }
    };

    /// <summary>
    /// Gets the <see cref="Icon"/> from its extension.
    /// </summary>
    /// <param name="extension">Extension of the file.</param>
    /// <returns>Returns the <see cref="Icon"/> from its extension.</returns>
    internal static Icon FromExtension(string? extension)
    {
        if (string.IsNullOrEmpty(extension))
        {
            return _iconsFromExtension["Default"];
        }

        if (_iconsFromExtension.TryGetValue(extension.ToLowerInvariant(), out var value) &&
            value is not null)
        {
            return value;
        }

        return _iconsFromExtension["Default"];
    }

    /// <summary>
    /// Gets the <see cref="Icon"/> from the <paramref name="extension"/> and <paramref name="view"/>.
    /// </summary>
    /// <param name="extension">Extension of the file.</param>
    /// <param name="view">View used from the <see cref="FluentCxFileManager{TItem}"/>.</param>
    /// <returns>Returns the <see cref="Icon"/> from its extension and its view.</returns>
    internal static Icon FromExtensionAndGridViewOptions(string? extension, FileView view)
    {
        if (string.IsNullOrEmpty(extension))
        {
            return _sizedGridOptionsIconFromExtensions[view]["Default"];
        }

        if (_sizedGridOptionsIconFromExtensions.TryGetValue(view, out var v) &&
            v.TryGetValue(extension.ToLowerInvariant(), out var value) &&
            value is not null)
        {
            return value;
        }

        return _sizedGridOptionsIconFromExtensions[view]["Default"];
    }

    /// <summary>
    /// Gets the folder <see cref="Icon"/> from the <paramref name="view"/>.
    /// </summary>
    /// <param name="view">View used from the <see cref="FluentCxFileManager{TItem}"/>.</param>
    /// <returns>Returns the <see cref="Icon"/> from its view.</returns>
    internal static Icon GetFolderFromGridViewOptions(FileView view)
    {
        return _sizedGridOptionsIconFromExtensions[view]["Folder"];
    }

    /// <summary>
    /// Gets the icons from the extension.
    /// </summary>
    /// <param name="extension">Extension of the file.</param>
    /// <param name="isDirectory">True if we want to have the folder icon.</param>
    /// <returns>Returns the <see cref="Icon"/> from its extension.</returns>
    internal static Icon GetIconForDetails(string? extension, bool isDirectory)
    {
        if (isDirectory)
        {
            return new Size128.FolderIcon();
        }

        if (string.IsNullOrEmpty(extension))
        {
            return new Size128.DefaultFileIcon();
        }

        if (_iconForDetailsPanel.TryGetValue(extension.ToLowerInvariant(), out var value) &&
            value is not null)
        {
            return value;
        }

        return _iconForDetailsPanel["Default"];
    }

    /// <summary>
    /// Convert the <see cref="Icon"/> value into an image source.
    /// </summary>
    /// <param name="icon">Icon to convert.</param>
    /// <returns>Returns the html image source from its icon.</returns>
    public static string ToImageSource(this Icon icon)
    {
        return $"data:image/svg+xml;base64,{Convert.ToBase64String(Encoding.UTF8.GetBytes(icon.Content))}";
    }
}

